In [4]:
import numpy as np
a=np.ones((3,3))
b=np.ones((3,1))
print(np.shape(np.dot(a,b)))
print(np.shape(np.matmul(a,b)))
c=np.array([1,2,3])
d=np.array([2,3,4])
print(np.dot(c,d))
print(np.matmul(c,d))
print("elemwise multiplication :",c*d)
import numpy as np
e=np.array([[2,4,6],[8,10,12]])
f=np.array([[1,2,3],[4,5,6]])
print(5.*e)
print(e*5)
print(e*f)

(3, 1)
(3, 1)
20
20
elemwise multiplication : [ 2  6 12]
[[10. 20. 30.]
 [40. 50. 60.]]
[[10 20 30]
 [40 50 60]]
[[ 2  8 18]
 [32 50 72]]
[[ 28  64]
 [ 64 154]]


In [6]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("array is ",arr)
print("use of size(total ele) and shape(ele in each dim) is ",arr.size,arr.shape)

array is  [[1 2 3]
 [4 5 6]
 [7 8 9]]
use of size(total ele) and shape(ele in each dim) is  9 (3, 3)


In [13]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("use of flatten ",arr.flatten())
print("use of transpose ",np.transpose(arr))
print("use of reshape(alter dim and no of ele in each dim)\n ",arr.reshape(3,1,3))

use of flatten  [1 2 3 4 5 6 7 8 9]
use of transpose  [[1 4 7]
 [2 5 8]
 [3 6 9]]
use of reshape(alter dim and no of ele in each dim)
  [[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]


In [9]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.reshape(-1))
print(arr.reshape(-1).T)
a=arr.reshape(-1)
print(a.shape)
b=a.T
print(b.shape)
print(a.ndim)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
(9,)
(9,)
1
